import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Sidebar from "./Components/Sidebar";
import "./globals.css";
import ContextProvider from "./Providers/ContextProvider";
import GlobalStyleProvider from "./Providers/GlobalStyleProvider";

const nunito = Nunito({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.className}
      >
        <ContextProvider>
          <GlobalStyleProvider>
            <Sidebar />
            {children}
          </GlobalStyleProvider>
        </ContextProvider>

      </body>
    </html>
  );
}
